name: raro_test
description: 'A new Flutter application.'

  # The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.

# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# We inserted the following format, for versioning control:

# <<YEAR>>.<<MILESTONE>>.<<FIXES>>.

# YEAR: represents the year of product launch, receiving the AAAA format.
# MILESTONE: represents the project milestone, being non-negative integers.
# FIXES: represents the bug fixes, being non-negative integers.

# All products will be launched with this version format, following the example: 2021.1.1
# To more info please visit our Handbook at https://handbook.snowmanlabs.com/desenvolvimento/qa/controle-de-versao.html
version: 2021.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  cupertino_icons:
  rx_notifier:
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  google_fonts: ^2.0.0
 # mobx_widget: ^0.4.2
  flutter_snow_base: ^2.2.2
  password_strength: ^0.2.0
  string_validator: ^0.3.0
  dio: ^4.0.0
  flutter_modular: ^3.1.0
  path_provider: ^2.0.1
  i18n_extension: ^4.0.3
  hive: ^2.0.4
  firebase_core: ^1.0.4
  injectable: ^1.2.2
  get_it: ^6.1.1
  flutter_svg:
  ezanimation: ^0.5.0
  flutter_keyboard_visibility: ^5.0.1
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  image_picker:

  flutter:
    sdk: flutter
  permission_handler: ^7.1.0


dependency_overrides:
#  analyzer: 0.41.2
  dart_style: 1.3.13
  build_resolvers: ^2.0.0
  package_config: ^2.0.0
  catcher: ^0.6.5
  flutter_mailer: 2.0.0-null-safe


dev_dependencies:
  build_runner: ^1.11.5
  mobx_codegen: ^2.0.1+3
  mockito: ^5.0.5
  injectable_generator: ^1.1.2
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

scripts:
  build_runner: flutter pub run build_runner build --delete-conflicting-outputs
  watch_runner: flutter pub run build_runner watch --delete-conflicting-outputs
  pubget_build_runner: flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs


